name: Test ir

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies for ir
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Install ir
        run: |
          curl -fsSL https://raw.githubusercontent.com/r-lib/ir/main/scripts/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Test ir (no deps)
        run: |
          ir --version
          ir run -e 'print(head(iris))'
